
###/menu/navigate###POST http://localhost:9999/vab-mock-server/menu/navigate
Content-Type: application/x-www-form-urlencoded
###

###/login###POST http://localhost:9999/vab-mock-server/login
Content-Type: application/x-www-form-urlencoded
###

###/ad/getList###POST http://localhost:9999/vab-mock-server/ad/getList
Content-Type: application/x-www-form-urlencoded
###

###/publicKey###POST http://localhost:9999/vab-mock-server/publicKey
Content-Type: application/x-www-form-urlencoded
###

###/user/info###POST http://localhost:9999/vab-mock-server/user/info
Content-Type: application/x-www-form-urlencoded
###

###/register###POST http://localhost:9999/vab-mock-server/register
Content-Type: application/x-www-form-urlencoded
###

###/logout###POST http://localhost:9999/vab-mock-server/logout
Content-Type: application/x-www-form-urlencoded
###
